name: Deploy to AWS ECS

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Build, Push, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Docker image to ECR
        run: |
          echo "deploying TestApp to AWS ECS"
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 329599656829.dkr.ecr.ap-south-1.amazonaws.com
          docker build -t testdog .
          docker tag testdog:latest 329599656829.dkr.ecr.ap-south-1.amazonaws.com/testdog:latest
          docker push 329599656829.dkr.ecr.ap-south-1.amazonaws.com/testdog:latest

          aws ecs update-service \
            --cluster testdog-cluster \
            --service testdog-api \
            --force-new-deployment \
            --region ap-south-1 \
            --task-definition testdog-api
